ControleBancario/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home/index'
  root 'home#index'
  post '/login' => "home#login", as: :login
  post '/logoff' => "home#logoff", as: :logoff
  resources :usuarios
  resources :cartoes
  resources :debitos
  resources :creditos
end

ControleBancario/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ControleBancario/app/models/cartao.rb
class Cartao < ApplicationRecord
  belongs_to :usuario
  has_many :creditos

  validates :nome, presence: { message: "Nome não pode ser vazio !" }
  validates :limite, presence: { message: "Limite não pode ser vazio !" }, numericality: { greater_than: 0, message: "Limite deve ser um número maior que zero !" }
end

ControleBancario/app/models/credito.rb
class Credito < ApplicationRecord
  belongs_to :cartao
  validate :limite_maximo
  after_validation :debitar_credito

  def limite_maximo
    errors.add :base, "Valor Limite Alcançado" if resultado_limite_atual<0
  end

  def debitar_credito
    cartao.limite_atual -= valor_creditado
    cartao.save 
  end

  def resultado_limite_atual
    return cartao.limite_atual - valor_creditado
  end
end

ControleBancario/app/models/debito.rb
class Debito < ApplicationRecord
  belongs_to :usuario
  validates :valor_debitado, presence: { message: "Valor não pode ser vazio !" }, numericality: { greater_than: 0, message: "Valor deve ser um número maior que zero !" }
  validates :local, presence: { message: "Nome não pode ser vazio !" }
  before_save :valor_limite_ce
  before_save :atualiza_saldo_total_usuario

  def atualiza_saldo_total_usuario
    usuario.saldo_total = valor_final
    usuario.save
  end
  def valor_limite_ce
    soma = usuario.limite_ce+valor_final
    if soma<0
      errors.add :base, "Valor Limite Alcançado"
    end
  end
  def valor_final
    qnt = valor_debitado
    qnt = (qnt*(-1)) if tipo_de_debito == "Retirada"
    return usuario.saldo_total + qnt
  end

end

ControleBancario/app/models/mensagem.rb
class Mensagem < ApplicationRecord
  belongs_to :usuario
end

ControleBancario/app/models/usuario.rb
class Usuario < ApplicationRecord
  has_many :cartoes
  has_many :debitos
  has_many :mensagens

  def self.validar_login(login, senha)
    Usuario.where(login: login, senha: senha).try(:take)
  end
  validates :nome, presence: { message: "Nome não pode ser vazio !" }
  validates :cpf, presence: { message: "CPF não pode ser vazio !" }
  validates :cpf, length: { is: 6, message: "CPF deve ter 11 números !" }
  validates :login, presence: { message: "Login não pode ser vazio !" }
  validates :senha, presence: { message: "Senha não pode ser vazia !" }
  validates :limite_ce, presence: { message: "Limite não pode ser vazio !" }, numericality: { greater_than: 99, message: "Limite deve ser ao menos 100 !" }

end

ControleBancario/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def verificar_login
    redirect_to home_index_path if session[:usuario_id] == nil
  end
  def usuario_atual
    if session[:usuario_id]
      Usuario.find(session[:usuario_id])
    end
  end
  def atualiza_valor_total
    session[:saldoAtual] = Usuario.find(session[:usuario_id]).saldo_total
  end
end

ControleBancario/app/controllers/cartoes_controller.rb
class CartoesController < ApplicationController
  before_action :verificar_login
  before_action :set_cartao , only: [:show]

  def new
    @cartao = Cartao.new
    @usuario = usuario_atual
  end

  def create
    @cartao = Cartao.new(cartao_params.merge({ usuario_id: session[:usuario_id], limite_atual: cartao_params[:limite] }))
    if @cartao.save
      redirect_to @cartao
    else
      render new_cartao_path
    end
  end

  def show
    
  end

  private

    def cartao_params
      params.require(:cartao).permit(:nome,:limite,:tipo_cartao)
    end

    def set_cartao
      @cartao = Cartao.find(params[:id])
    end
end

ControleBancario/app/controllers/creditos_controller.rb
class CreditosController < ApplicationController
  before_action :verificar_login

  def new
    @credito = Credito.new
  end

  def create
    @credito = Credito.new(credito_params)
    if @credito.save
      redirect_to @credito.cartao
    else
      render new_credito_path
    end
  end

  private
    def credito_params
      params.require(:credito).permit(:local, :valor_creditado, :cartao_id)
    end
end

ControleBancario/app/controllers/debitos_controller.rb
class DebitosController < ApplicationController
  before_action :verificar_login
  before_action :atualiza_valor_total

  def new
    @debito = Debito.new
    @usuario = usuario_atual
  end
  def create
    usuario = Usuario.find(debito_params[:usuario_id])
    puts "----------- SALTDO Q TO ADICIONADO -------> #{session[:saldoAtual]}"
    @debito = Debito.new(debito_params.merge({ saldo_total: session[:saldoAtual] }))
    if @debito.save
      redirect_to usuario
    else
      render new_debito_path
    end
  end
  private
    def debito_params
      params.require(:debito).permit(:local, :valor_debitado, :tipo_de_debito, :usuario_id)
    end
end

ControleBancario/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @usuario = Usuario.new
  end

  def login
    if @usuario = Usuario.validar_login(usuario_params[:login], usuario_params[:senha])
      session[:usuario_id] = @usuario.id
      session[:usuario_nome] = @usuario.nome
      session[:saldoAtual] = @usuario.saldo_total
      redirect_to @usuario
    else
      flash[:alert] = "Acesso negado. Login ou senha incorretos."
      redirect_to '/home/index'
    end
  end
  def logoff
    session[:usuario_id] = nil
    session[:usuario_nome] = nil
    session[:saldoAtual] = nil
    redirect_to home_index_path
  end

  private

    def usuario_params
      params.require(:usuario).permit(:nome, :cpf, :endereco, :login, :senha, :limite_ce)
    end
end

ControleBancario/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :verificar_login, only: [:show]
  before_action :atualiza_valor_total, only: [:show]
  
  def new
    @usuario = Usuario.new
  end

  def create
    if usuario_params[:senha] == usuario_params[:senha_confirm]
      @usuario = Usuario.new(usuario_params.except(:senha_confirm))
      if @usuario.save
        flash[:notice] = "Usuário criado."
        redirect_to '/home/index'
      else
        render new_usuario_path
      end
    else
      flash[:alert] = "Senha e confirmação de senha devem ser iguais !"
      redirect_to new_usuario_path
    end
  end

  def show
    @usuario = usuario_atual
    @mensagens = Mensagem.where(usuario: @usuario.id, status: false)
  end

  def edit
    @usuario = usuario_atual
  end

  def update
    if usuario_params[:senha] == usuario_params[:senha_confirm]
      @usuario = Usuario.update(usuario_params.except(:senha_confirm))
      if @usuario.save
        redirect_to nome_index_path
      else
        render edit_usuario_path(@usuario)
      end
    else
      flash[:alert] = "Senha e confirmação de senha devem ser iguais !"
      redirect_to new_usuario_path
    end
  end

  private

    def usuario_params
      params.require(:usuario).permit(:nome, :cpf, :endereco, :login, :senha, :senha_confirm, :limite_ce, :saldo_total)
    end

end

ControleBancario/app/helpers/application_helper.rb
module ApplicationHelper
end

ControleBancario/app/views/cartoes/new.html.erb
<h1>Cadastro de Cartão</h1>
<%= render 'shared/notice' %>
<%= bootstrap_form_for(@cartao) do |f| %>
    <%= f.text_field :nome %>
    <%= f.number_field :limite, step: :any %>
    <%= f.form_group :tipo_cartao, label: { text: "Tipo: " } do %>
      <%= f.radio_button :tipo_cartao, "cartaogold", label: "Cartão Gold", inline: true %>
      <%= f.radio_button :tipo_cartao, "cartaoprata", label: "Cartão Prata", inline: true %>
      <%= f.radio_button :tipo_cartao, "cartaoblack", label: "Cartão Black", inline: true %>
    <% end %>
    <%= f.submit "Cadastrar" %>
<% end %>
<br>
<%= link_to @usuario do %>
  <input type="button" class="btn btn-default" value="Voltar">
<% end %>

ControleBancario/app/views/cartoes/show.html.erb
<%= render 'shared/loginbar' %>
<div style="padding: 7px">
  <div class="page-header">
    <h2>Dados do cartão</h2>
  </div>
  <div class="row">

    <div class="col-sm-6">
      <b>Nome: </b><%= @cartao.nome %><br>
      <b>Tipo: </b><%= @cartao.tipo_cartao %><br>
      <b>Limite: </b><%= @cartao.limite %><br>
      <b>Limite atual </b><%= @cartao.limite_atual %><br>
    </div>
  </div>
  <div class="page-header"><h2>Débito</h2>

  <%= link_to new_credito_path(cartao_id: @cartao.id) do %>
    <button type="button" class="btn btn-primary">Novo Registro</button>
  <% end %>
  </div>
    <% if @cartao.creditos.count !=0 %>
      <table class="table">
        <thead>
          <tr>
            <th>Local</th>
            <th>Quantidade</th>
          </tr>
        </thead>
        <tbody>
        <% @cartao.creditos.each do |credito| %>
          <tr>
            <td><%= credito.local %></td>
            <td><%= credito.valor_creditado %></td>
          </tr>
        <% end %>
          <tr style="background-color: #EEEEEE">
            <td colspan="1">Total</td>
            <td><%= @cartao.limite_atual %></td>
          </tr> 
        </tbody>
      </table>
    <% else %>
      <div style="color: #AAAAAA">Cartão ainda não utilizado.</div>
    <% end %>
    <br>
    <%= link_to usuario_path do %>
      <input type="button" class="btn btn-default" value="Voltar">
    <% end %>
  <br>
  <br>
</div>

ControleBancario/app/views/creditos/new.html.erb
<%= render 'shared/erros', object: @credito %>
<div class="page-header"><h2>Novo Registro</h2></div>
  <%= bootstrap_form_for(@credito) do |f| %>
  <%= f.text_field :local %>
  <%= f.number_field :valor_creditado, step: :any %>
  <%= f.hidden_field :cartao_id, value: params[:cartao_id] %>
  <%= f.submit %>
<% end %>

ControleBancario/app/views/debitos/new.html.erb
<div class="page-header"><h2>Novo Registro</h2></div>
  <%= bootstrap_form_for(@debito) do |f| %>
  <%= f.text_field :local %>
  <%= f.number_field :valor_debitado, step: :any %>
  <%= f.hidden_field :usuario_id, value: session[:usuario_id] %>
  <%= f.form_group :tipo_de_debito, label: { text: "Tipo: " } do %>
    <%= f.radio_button :tipo_de_debito, "Retirada", label: "Retirada", inline: true %>
    <%= f.radio_button :tipo_de_debito, "Entrada", label: "Entrada", inline: true %>
  <% end %>
  <%= f.submit %>
<% end %>
<br>
<%= link_to @usuario do %>
  <input type="button" class="btn btn-default" value="Voltar">
<% end %>

ControleBancario/app/views/home/index.html.erb
<h1>Pagina de Login</h1>
<%= render 'shared/notice' %>
<%= bootstrap_form_for(@usuario, url: login_path) do |f| %>
  <div class="field">
    <%= f.text_field :login, autofocus: true %>
  </div>
  <div class="field">
    <%= f.password_field :senha %>
  </div>
  <div class="actions">
    <%= f.submit "Entrar" %>
  </div>
  <%= link_to "Cadastrar", new_usuario_path %>
<% end %>

ControleBancario/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ControleBancario</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'bootstrap.min.css' , 'bootstrap-theme.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'bootstrap.min.js' %>
    <style>
      html, body {
          max-width: 100%;
          overflow-x: hidden;
      }
    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

ControleBancario/app/views/shared/_erros.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger" id="DIV_alert_Error" role="alert">
    <div id="Msg_Alert_Error">
     O formulário contêm <%= pluralize(object.errors.count, "erro") %>:
     <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
     <% end %>
     </ul>
   </div>
 </div>
<% end %>

ControleBancario/app/views/shared/_loginbar.html.erb
    <% if session[:usuario_id] %>
      <div style="position: absolute; right: 0px; padding: 10px">
        Olá <b> <%= link_to session[:usuario_nome], edit_usuario_path(session[:usuario_id]) %></b> |
        <%= link_to "Logoff", logoff_path, method: :post %>
      </div>
    <% end %>

ControleBancario/app/views/shared/_notice.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <div>
      <strong>Sucesso !</strong> <%= flash[:notice] %>
    </div>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger" role="alert">
    <div>
      <strong>Atenção !</strong> <%= flash[:alert] %>
    </div>
  </div>
<% end %>

ControleBancario/app/views/usuarios/edit.html.erb
<h1>Cadastro de Usuario</h1>
<%= render 'shared/notice' %>
<%= bootstrap_form_for(@usuario) do |f| %>
    <%= f.text_field :nome %>
    <%= f.text_field :cpf %>
    <%= f.text_field :endereco %>
    <%= f.text_field :login %>
    <%= f.password_field :senha %>
    <%= f.password_field :senha_confirm %>
    <%= f.number_field :limite_ce, label: "Limite de cheque especial", step: :any %>
    <%= f.hidden_field :saldo_total, label: "Limite de cheque especial", value: 0 %>
    <%= f.submit "Salvar" %>
<% end %>

ControleBancario/app/views/usuarios/new.html.erb
<h1>Cadastro de Usuario</h1>
<%= render 'shared/notice' %>
<%= bootstrap_form_for(@usuario) do |f| %>
    <%= f.text_field :nome %>
    <%= f.text_field :cpf %>
    <%= f.text_field :endereco %>
    <%= f.text_field :login %>
    <%= f.password_field :senha %>
    <%= f.password_field :senha_confirm %>
    <%= f.number_field :limite_ce, label: "Limite de cheque especial", step: :any %>
    <%= f.hidden_field :saldo_total, label: "Limite de cheque especial", value: 0 %>
    <%= f.submit "Cadastrar" %>
<% end %>
<br>
<%= link_to home_index_path do %>
  <input type="button" class="btn btn-default" value="Voltar">
<% end %>

ControleBancario/app/views/usuarios/show.html.erb
<%= render 'shared/loginbar' %>
<div style="padding: 7px">
  <div class="page-header">
    <h1>Dados Pessoais</h1>
  </div>
  <div class="row">
    <div class="col-sm-2">
      <img src="/image/user.png" class="img-thumbnail">
    </div>
    <div class="col-sm-6">
      <b>Nome: </b><%= @usuario.nome %><br>
      <b>CPF: </b><%= @usuario.cpf %><br>
      <b>Endereço: </b><%= @usuario.endereco %><br>
      <b>Limite do cheque especial: </b><%= @usuario.limite_ce %><br>
      <b>Saldo atual: </b><%= @usuario.saldo_total %><br>
    </div>
  </div>
  <div class="page-header"><h2>Conta Bancária</h2>

  <%= link_to new_debito_path do %>
    <button type="button" class="btn btn-primary">Novo Registro</button>
  <% end %>
  </div>
    <% if @usuario.debitos.count !=0 %>
      <table class="table">
        <thead>
          <tr>
            <th>Local</th>
            <th>Quantidade</th>
            <th>Saldo Anterior</th>
          </tr>
        </thead>
        <tbody>
        <% @usuario.debitos.each do |debito| %>
          <tr>
            <td><%= debito.local %></td>
            <td><%= debito.valor_debitado %></td>
            <td><%= debito.saldo_total %></td>
          </tr>
        <% end %>
          <tr style="background-color: #EEEEEE">
            <td colspan="2">Total</td>
            <td><%= @usuario.saldo_total %></td>
          </tr> 
        </tbody>
      </table>
    <% else %>
      <div style="color: #AAAAAA">Conta ainda não utilizada.</div>
    <% end %>
  <div class="page-header"><h2>Cartões</h2>
    <%= link_to new_cartao_path do %>
      <button type="button" class="btn btn-primary">Novo Cartão</button>
    <% end %>
  </div>
    <% if @usuario.cartoes.count !=0 %>
      <table class="table">
        <thead>
          <tr>
            <th>Nome</th>
            <th>Tipo</th>
            <th>Limite</th>
            <th>Limite Atual</th>
          </tr>
        </thead>
        <tbody>
        <% @usuario.cartoes.each do |cartao| %>
          <tr>
            <td><%= link_to cartao.nome, cartao %></td>
            <td><%= cartao.tipo_cartao %></td>
            <td><%= cartao.limite %></td>
            <td><%= cartao.limite_atual %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
      <div style="color: #AAAAAA">Não há cartões nesta conta.</div>
    <% end %>
  <div class="page-header"><h2>Mensagens</h2></div>

  <% if @mensagens.count != 0 %>

    <% @mensagens.each do |mensagem| %>
      <% if mensagem.tipo == "S" %>
        <div class="alert alert-success" role="alert">
          <div>
            <%= mensagem.msg %>
            <span class="label label-default" style="position: absolute; right:20px; ">X</span>
          </div>
        </div>
      <% elsif mensagem.tipo == "I" %>
        <div class="alert alert-info" role="alert">
          <div>
            <%= mensagem.msg %>
            <span class="label label-default" style="position: absolute; right:20px; ">X</span>
          </div>
        </div>
      <% elsif mensagem.tipo == "W" %>
        <div class="alert alert-warning" role="alert">
          <div>
            <%= mensagem.msg %>
            <span class="label label-default" style="position: absolute; right:20px; ">X</span>
          </div>
        </div>
      <% elsif mensagem.tipo == "D" %>
        <div class="alert alert-danger" role="alert">
          <div>
            <%= mensagem.msg %>
            <span class="label label-default" style="position: absolute; right:20px; ">X</span>
          </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <div style="color: #AAAAAA">Não há mensagens novas.</div>
  <% end %>
  <br>
  <br>
</div>